vendor/Makefile: page-to-alto is phony
UB-Mannheim/ocr-fileformat pull request #154
Opened 2022-11-07 14:46 UTC by bertsky

fixes #153

2022-11-07 14:49 UTC, kba approved these changes

2022-11-07 15:17 UTC, stweil reviewed
I am not sure that this is the right fix (even if it seems to fix the problem). `gcv2hocr` is missing, too. And I also did not find a regression. Did the installation ever work before? If yes, with which version?

2022-11-08 06:42 UTC, stweil requested changes

2022-11-08 06:42 UTC, stweil commented on vendor/Makefile
> +.PHONY: all check $(PAGE_SCHEMA_REPO) $(ABBYY_SCHEMA_REPO) page-to-alto
```suggestion
.PHONY: all check $(PAGE_SCHEMA_REPO) $(ABBYY_SCHEMA_REPO) gcv2hocr page-to-alto
```

2022-11-08 07:05 UTC, stweil commented
In the old code the installation of `page-to-alto` was a side effect of `make all`. `make install` (which also respects `DESTDIR`) had no effect on its installation.

The suggested pull request restores the old behaviour partially. With my addition, it also restores `make` for `gcv2hocr` (which is built, but never installed).

2022-11-08 07:30 UTC, stweil commented
`gcv2hocr` needs one more fix. Therefore I merge now and apply that fix on top.

2022-11-08 07:30 UTC, merged